import express, { Request, Response } from 'express';
import cors from 'cors';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import dotenv from 'dotenv';
import path from 'path';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { fileURLToPath } from 'url';
import { ApiResponse } from '../../shared/types.js';
import { connectDB } from './config/db.js';
import { seedDatabase } from './config/seed.js';
import { logger, loggerMiddleware } from './middleware/logger.js';
import { errorHandler } from './middleware/errorHandler.js';

// Routes
import authRoutes from './routes/authRoutes.js';
import resourceRoutes from './routes/resourceRoutes.js';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 4000;

// Connect to Database & Seed 4 Initial Collections
connectDB().then(() => {
  seedDatabase();
});

// Security Middleware
app.use(helmet());
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  message: 'Too many requests from this IP, please try again after 15 minutes',
});
app.use('/api/', limiter);

// Standard Middleware
app.use(cors());
app.use(cookieParser());
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(express.json());
app.use(loggerMiddleware);

// API Routes
app.use('/api/auth', authRoutes);
app.use('/api/resources', resourceRoutes);

// Health Check & Root API Endpoints
app.get(['/api', '/api/health'], (req: Request, res: Response) => {
  const response: ApiResponse = { status: 'ok', message: 'D-Stack API is running' };
  res.json(response);
});

// Interactive OpenAPI / Swagger Documentation
app.get('/api/docs/json', (req: Request, res: Response) => {
  res.json({
    openapi: '3.0.0',
    info: {
      title: 'D-Stack Application API',
      version: '1.0.0',
      description: 'Interactive API documentation generated by D-Stack Framework',
    },
    paths: {
      '/api/health': {
        get: { summary: 'Health Check Endpoint', responses: { '200': { description: 'API is running' } } }
      },
      '/api/auth/login': {
        post: { summary: 'User Login', responses: { '200': { description: 'Returns JWT token and User info' } } }
      },
      '/api/auth/register': {
        post: { summary: 'User Registration', responses: { '201': { description: 'Returns created User and JWT token' } } }
      },
      '/api/resources': {
        get: { summary: 'Get all resources', responses: { '200': { description: 'List of items' } } },
        post: { summary: 'Create a new resource', responses: { '201': { description: 'Created item' } } }
      }
    }
  });
});

app.get('/api/docs', (req: Request, res: Response) => {
  res.send(`
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>⚡ D-Stack API Documentation</title>
      <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
      <style>
        body { margin: 0; padding: 0; background: #0f172a; }
        .swagger-ui .topbar { display: none; }
        .swagger-ui { filter: invert(88%) hue-rotate(180deg); }
      </style>
    </head>
    <body>
      <div id="swagger-ui"></div>
      <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
      <script>
        window.onload = () => {
          SwaggerUIBundle({
            url: '/api/docs/json',
            dom_id: '#swagger-ui',
          });
        };
      </script>
    </body>
    </html>
  `);
});

// Production: Serve Frontend
if (process.env.NODE_ENV === 'production') {
  const staticPath = path.join(__dirname, '../../web/dist');
  app.use(express.static(staticPath));
  
  app.get('*', (req: Request, res: Response) => {
    res.sendFile(path.join(staticPath, 'index.html'));
  });
}

// Global Error Handler (Must be last)
app.use(errorHandler);

export { app };

app.listen(PORT, () => {
  logger.info(`🚀 TS Server running on http://localhost:${PORT}`);
});
